version: 0.1.{build}

branches:
  only:
    - master
    
image: Visual Studio 2017

clone_folder: c:\projects\CharGen

matrix:
  fast_finish: true
  
configuration: Release
  
build:
  parallel: true
  project: CharGen.sln
  publish_wap_xcopy: true
  verbosity: minimal

before_build:
  - cmd: dotnet restore
  
test:
  assemblies:
    only:
      - CharGen.UnitTests.dll
test_script:
  - cmd: cd CharGen.UnitTests & dotnet test -c Release -v q --no-build
      
after_test:
- cmd: cd .. & cd CharGen.Storyteller & dotnet run -- run --tracing appveyor
- cmd: cd .. & dotnet publish ADD2CharacterService -c Release -o ./publish
      
artifacts:
- path: ADD2CharacterService/publish
  name: publish
- path: CharGen.Storyteller/stresults.htm
  name: StorytellerResults.htm