version: 0.1.{build}

branches:
  only:
    - master
    
image: Visual Studio 2017

matrix:
  fast_finish: true
  
install:
  - cmd: dotnet restore
  
configuration: Release
  
build:
  parallel: true
  project: CharGen.sln
  publish_wap_xcopy: true
  verbosity: minimal
  
test_script:
  - cmd: cd CharGen.UnitTests & dotnet test -c Release -v q --no-build
      
after_test:
- cmd: cd .. & cd CharGen.Storyteller & dotnet run -- run --tracing appveyor
- cmd: cd .. & dotnet publish ADD2CharacterService -c Release -o ./add2publish
- cmd: dotnet publish DD35CharacterService -c Release -o ./dd35publish
      
artifacts:
- path: ADD2CharacterService/add2publish
  name: add2publish
- path: DD35CharacterService/dd35publish
  name: dd35publish
- path: CharGen.Storyteller/stresults.htm
  name: StorytellerResults.htm