version: 0.1.{build}

branches:
  only:
    - master
    
image: Visual Studio 2017

environment:
  COVERALLS_REPO_TOKEN:
    secure: xSBmCtrGxxcXGKHbsHZp405e+uUajre5pNH/esifQvEzLpLmcHuH2vMIkAURqWyY

matrix:
  fast_finish: true
  
install:
  - cmd: dotnet tool install -g coveralls.net --version 1.0.0
  - cmd: dotnet tool install -g dotnet-reportgenerator-globaltool
  - cmd: dotnet restore
  
configuration: Release
  
build:
  parallel: true
  project: CharGen.sln
  publish_wap_xcopy: true
  verbosity: minimal
  
test_script:
  - cmd: dotnet test CharGen.UnitTests -c Release -v q --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - cmd: reportgenerator -reports:coverage.opencover.xml -reporttypes:Xml -targetdir:coveragereport -filefilters:-Program.cs
  - cmd: dotnet run -p CharGen.Storyteller -- run --tracing appveyor
      
after_test:
  - cmd: csmacnz.Coveralls.exe --reportgenerator -i CharGen.UnitTests/coveragereport --useRelativePaths
  - cmd: dotnet publish ADD2CharacterService -c Release -o ./add2publish
  - cmd: dotnet publish DD35CharacterService -c Release -o ./dd35publish
      
artifacts:
  - path: ADD2CharacterService/add2publish
    name: add2publish
  - path: DD35CharacterService/dd35publish
    name: dd35publish
  - path: stresults.htm
    name: StorytellerResults.htm