version: 0.1.{build}

branches:
  only:
    - master
    
image: Visual Studio 2017

clone_folder: c:\projects\CharGen

matrix:
  fast_finish: true
  
build:
  parallel: true
  project: CharGen.sln
  publish_wap_xcopy: true

before_build:
  - dotnet restore
  
test:
  assemblies:
    only:
      - CharGen.UnitTests.dll